import { GameCategory } from "@prisma/client";

export interface CatalogGame {
  slug: string;
  name: string;
  provider: string;
  category: GameCategory;
  rtp: number;
  minBet: number;
  maxBet: number;
}

export const GAME_CATALOG: CatalogGame[] = [
  // Slots
  {
    slug: "mega-fortune",
    name: "Mega Fortune",
    provider: "SlotsOne",
    category: "SLOTS",
    rtp: 96.4,
    minBet: 0.1,
    maxBet: 100,
  },
  {
    slug: "book-of-dead",
    name: "Book of Dead",
    provider: "Play'n GO",
    category: "SLOTS",
    rtp: 96.21,
    minBet: 0.1,
    maxBet: 100,
  },
  {
    slug: "sweet-bonanza",
    name: "Sweet Bonanza",
    provider: "Pragmatic Play",
    category: "SLOTS",
    rtp: 96.51,
    minBet: 0.1,
    maxBet: 100,
  },
  {
    slug: "gates-of-olympus",
    name: "Gates of Olympus",
    provider: "Pragmatic Play",
    category: "SLOTS",
    rtp: 96.5,
    minBet: 0.1,
    maxBet: 100,
  },
  {
    slug: "starburst",
    name: "Starburst",
    provider: "NetEnt",
    category: "SLOTS",
    rtp: 96.09,
    minBet: 0.1,
    maxBet: 100,
  },
  {
    slug: "gonzos-quest",
    name: "Gonzo's Quest",
    provider: "NetEnt",
    category: "SLOTS",
    rtp: 95.97,
    minBet: 0.1,
    maxBet: 100,
  },
  {
    slug: "dead-or-alive-2",
    name: "Dead or Alive 2",
    provider: "NetEnt",
    category: "SLOTS",
    rtp: 96.82,
    minBet: 0.1,
    maxBet: 100,
  },
  {
    slug: "reactoonz",
    name: "Reactoonz",
    provider: "Play'n GO",
    category: "SLOTS",
    rtp: 96.51,
    minBet: 0.1,
    maxBet: 100,
  },
  {
    slug: "jammin-jars",
    name: "Jammin' Jars",
    provider: "Push Gaming",
    category: "SLOTS",
    rtp: 96.83,
    minBet: 0.1,
    maxBet: 100,
  },
  {
    slug: "big-bass-bonanza",
    name: "Big Bass Bonanza",
    provider: "Pragmatic Play",
    category: "SLOTS",
    rtp: 96.71,
    minBet: 0.1,
    maxBet: 100,
  },
  {
    slug: "wolf-gold",
    name: "Wolf Gold",
    provider: "Pragmatic Play",
    category: "SLOTS",
    rtp: 96.01,
    minBet: 0.1,
    maxBet: 100,
  },
  {
    slug: "fire-joker",
    name: "Fire Joker",
    provider: "Play'n GO",
    category: "SLOTS",
    rtp: 96.15,
    minBet: 0.1,
    maxBet: 100,
  },
  // Roulette → TABLE
  {
    slug: "european-roulette",
    name: "European Roulette",
    provider: "Evolution",
    category: "TABLE",
    rtp: 97.3,
    minBet: 0.1,
    maxBet: 500,
  },
  {
    slug: "american-roulette",
    name: "American Roulette",
    provider: "Evolution",
    category: "TABLE",
    rtp: 94.74,
    minBet: 0.1,
    maxBet: 500,
  },
  {
    slug: "french-roulette",
    name: "French Roulette",
    provider: "Evolution",
    category: "TABLE",
    rtp: 98.65,
    minBet: 0.1,
    maxBet: 500,
  },
  {
    slug: "lightning-roulette",
    name: "Lightning Roulette",
    provider: "Evolution",
    category: "TABLE",
    rtp: 97.3,
    minBet: 0.1,
    maxBet: 500,
  },
  {
    slug: "vip-roulette",
    name: "VIP Roulette",
    provider: "Evolution",
    category: "TABLE",
    rtp: 97.3,
    minBet: 0.1,
    maxBet: 500,
  },
  {
    slug: "speed-roulette",
    name: "Speed Roulette",
    provider: "Evolution",
    category: "TABLE",
    rtp: 97.3,
    minBet: 0.1,
    maxBet: 500,
  },
  // Blackjack → TABLE
  {
    slug: "classic-blackjack",
    name: "Classic Blackjack",
    provider: "Evolution",
    category: "TABLE",
    rtp: 99.5,
    minBet: 0.5,
    maxBet: 1000,
  },
  {
    slug: "vip-blackjack",
    name: "VIP Blackjack",
    provider: "Evolution",
    category: "TABLE",
    rtp: 99.5,
    minBet: 1,
    maxBet: 5000,
  },
  {
    slug: "infinite-blackjack",
    name: "Infinite Blackjack",
    provider: "Evolution",
    category: "TABLE",
    rtp: 99.47,
    minBet: 0.5,
    maxBet: 1000,
  },
  {
    slug: "multi-hand-blackjack",
    name: "Multi-Hand Blackjack",
    provider: "Pragmatic Play",
    category: "TABLE",
    rtp: 99.4,
    minBet: 0.5,
    maxBet: 1000,
  },
  {
    slug: "perfect-pairs-blackjack",
    name: "Perfect Pairs",
    provider: "Evolution",
    category: "TABLE",
    rtp: 99.18,
    minBet: 0.5,
    maxBet: 1000,
  },
  // Baccarat → TABLE
  {
    slug: "classic-baccarat",
    name: "Classic Baccarat",
    provider: "Evolution",
    category: "TABLE",
    rtp: 98.94,
    minBet: 1,
    maxBet: 5000,
  },
  {
    slug: "speed-baccarat",
    name: "Speed Baccarat",
    provider: "Evolution",
    category: "TABLE",
    rtp: 98.94,
    minBet: 1,
    maxBet: 5000,
  },
  {
    slug: "vip-baccarat",
    name: "VIP Baccarat",
    provider: "Evolution",
    category: "TABLE",
    rtp: 98.94,
    minBet: 5,
    maxBet: 10000,
  },
  {
    slug: "squeeze-baccarat",
    name: "Squeeze Baccarat",
    provider: "Evolution",
    category: "TABLE",
    rtp: 98.94,
    minBet: 1,
    maxBet: 5000,
  },
  {
    slug: "no-commission-baccarat",
    name: "No Commission Baccarat",
    provider: "Evolution",
    category: "TABLE",
    rtp: 98.76,
    minBet: 1,
    maxBet: 5000,
  },
];

const catalogBySlug = new Map(GAME_CATALOG.map((g) => [g.slug, g]));

export function getCatalogGame(slug: string): CatalogGame | undefined {
  return catalogBySlug.get(slug);
}
